services:
  - docker

branches:
  only:
    - master

os:
  - linux

env:
  global:
    - DATE=`TZ=America/New_York date "+%Y-%m-%d-%H%M"`
    - DOCKER_IMAGE="leanda/reaction-file-parser"
    - DOCKER_TESTS_IMAGE="leanda/reaction-parser-tests"

script:
  - docker build -t $DOCKER_IMAGE:$DATE -t $DOCKER_IMAGE:latest .
  - cd tests/Sds.ReactionFileParser.Tests && docker build -t $DOCKER_TESTS_IMAGE:latest -f Sds.ReactionFileParser.Tests/Dockerfile .
  - yes | cp -rf Sds.ReactionFileParser.Tests/.env.travis-ci Sds.ReactionFileParser.Tests/.env
  - cd Sds.ReactionFileParser.Tests && docker-compose up --abort-on-container-exit

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_IMAGE # Pushes both date and latest
